version: "3"
services:
  web:
    image: "nginx:1.15.2-alpine"
    volumes:
      - ".:/var/www/html"
      - "./nginx/:/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node
  node:
    image: "node:8.11.3-alpine"
    volumes:
      - ".:/var/www/html"
    working_dir: /var/www/html
    entrypoint: /bin/sh /var/www/html/build.sh

