version: "3"

services:
  resume:
    image: "nginx:1.15.2-alpine"
    volumes:
      - ".:/var/www/html"
      - "./nginx/resume.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - node
    ports:
      - "80:80"
  node:
    image: "node:8.11.3-alpine"
    volumes:
      - ".:/var/www/html"
    working_dir: /var/www/html
    entrypoint: /bin/sh /var/www/html/build.sh


