version: "3"
services:
  nginx:
    container_name: "nginx"
    image: "nginx:alpine"
    volumes:
      - ".:/var/www/html"
      - "./nginx/:/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"
